<?php
/** @var \Magenest\Study\Block\MovieTable $block */
$arrayData = $block->getMovie();
?>
<table>
    <tr>
        <th>Movie</th>
        <th>Director</th>
        <th>Actor</th>
        <th>Description</th>
        <th>Rating</th>
    </tr>
    <?php
    foreach ($arrayData as $row) {
        echo
            "<tr>
          <td>" . $row['name'] . "</td>
          <td>" . $row['director_name'] . "</td>
          <td>" . $row['actor_name'] . "</td>
          <td>" . $row['description'] . "</td>
          <td>" . $row['rating'] . "</td>
         </tr>";
    }
    ?>
</table>

