<legend><h1 >data</h1></legend>
<table style="width: 50%;" class="data-table" data-role="grid">

    <tbody>
    <tr>
        <th>Num of Products  :</th>
        <th><?php echo $block->getProductNumber(); ?></th>
    </tr>
    <tr>
        <th >Num of Orders  :</th>
        <th ><?php echo $block->getOrderNumber(); ?></th>
    </tr>
    <tr>
        <th>Num of Invoices :</th>
        <th><?php echo $block->getInvoiceNumber(); ?></th>
    </tr>
    <tr>
        <th ">Num of  Creditmemos  :</th>
        <th "><?php echo $block->getCreditMemoNumber(); ?></th>
    </tr>
    <tr>
        <th>Num of Customers  :</th>
        <th><?php echo $block->getCustomerNumber(); ?></th>
    </tr>
    </tbody>

</table>